module.exports = {
  darkMode: 'class',
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        surface: '#e8fff0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#d1fee5',
        'surface-container': '#ccf8df',
        'surface-container-high': '#c6f2da',
        'on-surface': '#002114',
        'on-surface-variant': '#3f4943',
        outline: '#6f7a72',
        'outline-variant': '#bec9c0',
        primary: '#0b6947',
        'on-primary': '#ffffff',
        'primary-container': '#30835f',
        'on-primary-container': '#f5fff6',
        secondary: '#605f50',
        'on-secondary': '#ffffff',
        'secondary-container': '#e6e3d0',
        'on-secondary-container': '#666556',
        tertiary: '#7d532d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#986b42',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#e8fff0',
        'on-background': '#002114',
      },
      fontFamily: {
        lexend: ['Lexend', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em' }],
        'headline-sm': ['20px', { lineHeight: '28px' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-lg': ['14px', { lineHeight: '16px', letterSpacing: '0.02em' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.04em' }],
      },
      spacing: {
        margin: '1.25rem',
        gutter: '1rem',
      },
    },
  },
  plugins: [],
};
